version: 1.{build}
skip_tags: true
image: Visual Studio 2022
configuration: Release
init:
- ps: ''
install:
- cmd: >-
    git submodule update --init --recursive

    premake5.bat
before_build:
- ps: >-
    msbuild -m build/XboxRainDropletsWrapper.sln /property:Configuration=Release /property:Platform=Win32

    msbuild -m build/XboxRainDropletsWrapper.sln /property:Configuration=Release /property:Platform=Win64


    Start-FileDownload https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/download/Win32-latest/version-Win32.zip

    Start-FileDownload https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/download/x64-latest/dinput8-x64.zip

    Start-FileDownload https://github.com/ThirteenAG/WidescreenFixesPack/releases/download/xrd/PCSX2F.XboxRainDroplets.zip

    Start-FileDownload https://github.com/ThirteenAG/WidescreenFixesPack/releases/download/xrd/PPSSPP.XboxRainDroplets.zip
build:
  project: build/XboxRainDroplets.sln
  verbosity: minimal
before_package:
- cmd: >-
    7z x version-Win32.zip -obin/ -y

    7z x dinput8-x64.zip -obin/ -y

    7z x PCSX2F.XboxRainDroplets.zip -obin/ -y

    7z x PPSSPP.XboxRainDroplets.zip -obin/ -y

    del version-Win32.zip

    del dinput8-x64.zip

    del PCSX2F.XboxRainDroplets.zip

    del PPSSPP.XboxRainDroplets.zip


    release.bat
after_build:
- ps: Get-ChildItem .\bin\*.zip  | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }