#pragma once
// ---------------------------------------------------------------------------
// Shader sources.
//
// One small shader per API family, all of them doing the same thing as the
// two texture stages of the original code: modulate the vertex colour with the
// atlas of drop shapes, then modulate that with the copy of the frame behind
// the drop. Snow takes the complement of the frame instead, which is what kept
// it bright on the console versions.
//
//   Direct3D 8  embedded shader model 1, or fixed function fallback
//   Direct3D 9  embedded shader model 3, or fixed function fallback
//   Direct3D 10 shader model 4, compiled at build time
//   Direct3D 11 shader model 4, compiled at build time
//   Direct3D 12 shader model 5, compiled at build time
//   OpenGL      GLSL 1.20, compiled at runtime by the driver
//   Vulkan      SPIR-V, compiled while building with dxc
// Direct3D bytecode is generated by tools/CompileDropletShaders.ps1 and embedded
// by Dropmask.rc. Keep these sources as the single input to that build step.
// ---------------------------------------------------------------------------

namespace Xrd
{
    namespace Shaders
    {
        // Direct3D 10 and above. The vertex buffer holds
        //   float3 position, uint color, float2 atlas, float2 scene
        // which is exactly the Vertex type.
        //
        // A drop of clear water is a lens of the colour of what is around it: the
        // vertex shader gathers the light of the frame around the drop and hands
        // it to the pixel shader, which adds it to the refracted backdrop. The
        // gather is per vertex because four vertices per drop are affordable
        // while a per pixel one would not be, and it is smooth enough to read as
        // the colour of a light, which is what it is for.
        //
        // Only the drops of clear rain gather light. The effect says so by
        // handing the atlas coordinate of such a drop over moved down by
        // AtlasLightMarker, see WaterDrops::AddToRenderList: the atlas is
        // sampled at whole numbers and above zero, so a negative coordinate is
        // one no drop of its own ever has.
        inline const char* D3D11Source = R"(
cbuffer XrdConstants : register(b0)
{
    float4x4 projection;
    float4 uvOffset;
    float4 uvScale;
    float4 sceneComplement;
};

Texture2D sceneTexture : register(t0);
Texture2D maskTexture : register(t1);
SamplerState linearClamp : register(s0);

// how far the atlas coordinate of a drop that gathers light was moved down,
// and back up again, see WaterDrops::AddToRenderList
static const float AtlasLightMarker = 2.0f;

// The gather is a grid of cells over a square around the drop, in fractions of
// the target, and every cell is the average of four samples of the whole cell
// rather than one sample of a point of it: a small light is then found wherever
// the cells happen to fall, so the colour a drop takes does not jump about as
// the scenery moves past it, which is what one sample per cell looks like.
static const float LightRadius = 0.14f;
static const int LightCells = 8;

// What a drop adds to what it shows is the light of the frame around it that
// stands out of that frame, and nothing else: a frame that is bright is not a
// light, so a drop in a bright frame is the colour of water. LightFloor is how
// much brighter than the frame around it a light has to be to count at all, and
// the ramp is how much of it there has to be to light a drop up in full: a lamp of
// a night city stands out of what is around it by a lot, so the ramp has to be
// over well below its kind of brightness or the whole of it never arrives.
static const float LightFloor = 1.25f;
static const float LightRampLow = 0.03f;
static const float LightRampHigh = 0.20f;

// How much of the colour of a light a drop keeps. What a lens does with a colour
// is to keep it, and what washes the colour out of a drop is the grey of the
// whole neighbourhood the light was measured against, so the colour that was left
// over is pushed back out of its own grey: a tail light is then a red drop and
// not a grey one with a warm tint, and a white light, which has no colour to push
// out, is left exactly as it was. Nothing about which places of the frame count
// as a light changes here, so a drop takes on no new colour from one frame to the
// next and nothing flickers.
static const float LightChroma = 2.5f;

struct VSInput
{
    float3 position : POSITION;
    float4 color : COLOR;
    float2 atlas : TEXCOORD0;
    float2 scene : TEXCOORD1;
};

struct VSOutput
{
    float4 position : SV_POSITION;
    float4 color : COLOR;
    float2 atlas : TEXCOORD0;
    float2 scene : TEXCOORD1;
    float3 light : TEXCOORD2;
};

VSOutput VSMain(VSInput input)
{
    VSOutput output;
    output.position = mul(projection, float4(input.position, 1.0f));
    output.color = input.color;
    output.atlas = input.atlas;
    output.scene = input.scene * uvScale.xy + uvOffset.xy;
    output.light = 0.0f;

    if (input.atlas.x < -0.5f)
    {
        // the atlas coordinate the drop really has, the marker is only a flag
        output.atlas.x += AtlasLightMarker;

        // where the drop is on the target, in the coordinates of the copy of the
        // frame the pixel shader samples. The uvOffset and uvScale of the
        // constants are the crop a game asks the refraction to sample, and they
        // are deliberately not applied here: a light is where it is on the
        // screen, and moving the field a light is looked up in by the crop of
        // the refraction would light every drop up from the wrong place.
        float2 lightUV = output.position.xy / output.position.w * float2(0.5f, -0.5f) + 0.5f;

        // the same reach around the drop in pixels, on a target of any shape
        float aspect = abs(projection[1][1] / projection[0][0]);
        float2 radius = float2(LightRadius / max(aspect, 0.1f), LightRadius);
        float2 cell = radius / LightCells;

        // The grid is aligned to the target and not to the drop, so a drop that
        // moves gathers its light from the very same places of the frame and the
        // field does not crawl over the scenery with it.
        float2 anchor = floor(lightUV / cell) * cell;

        // the light of the frame around the drop, the plain colour of it, and
        // how much of each there was found
        float3 energy = 0.0f;
        float3 plain = 0.0f;
        float weight = 0.0f;
        float falloffSum = 0.0f;

        [loop] for (int y = -LightCells; y <= LightCells; ++y)
        {
            [loop] for (int x = -LightCells; x <= LightCells; ++x)
            {
                float2 corner = anchor + float2(x, y) * cell;
                float2 offset = (corner - lightUV) / radius;
                float distance2 = dot(offset, offset);

                // a soft kernel that is cut off where it is small anyway, so the
                // edge of the reach of a drop is not a visible circle
                float falloff = exp2(-2.0f * distance2) * (1.0f - smoothstep(0.75f, 1.0f, distance2));

                // what the frame holds over the whole cell
                float3 source = sceneTexture.SampleLevel(linearClamp, corner + float2(-0.25f, -0.25f) * cell, 0).rgb;
                source += sceneTexture.SampleLevel(linearClamp, corner + float2(0.25f, -0.25f) * cell, 0).rgb;
                source += sceneTexture.SampleLevel(linearClamp, corner + float2(-0.25f, 0.25f) * cell, 0).rgb;
                source += sceneTexture.SampleLevel(linearClamp, corner + float2(0.25f, 0.25f) * cell, 0).rgb;
                source *= 0.25f;

                float brightness = max(source.r, max(source.g, source.b));
                float saturation = (brightness - min(source.r, min(source.g, source.b))) / max(brightness, 0.001f);

                // How much light there is in what the cell holds and how coloured
                // it is. There is deliberately no brightness a cell has to pass to
                // count: a light fades in with the distance like everything else,
                // and nothing about the colour of a drop flickers while a light
                // comes into its reach or leaves it.
                float w = brightness * brightness * (1.0f + saturation) * falloff;

                energy += source * w;
                plain += source * falloff;
                weight += w;
                falloffSum += falloff;
            }
        }

        // Two averages of the very same surroundings of the drop: the one weighted
        // by how much light is in them and the plain one. A frame that is bright
        // all over gives the same for both and adds nothing to a drop, which is
        // what keeps a drop in a bright frame the colour of water instead of
        // white, and only what stands out of the frame around the drop is added to
        // it, which is what a drop of water collects out of a lamp.
        float3 gathered = energy / (weight + 0.5f);
        float3 average = plain / max(falloffSum, 0.001f);

        // The frame itself is taken off, and a foot is put under what is left of
        // it, because a half of a frame that happens to be brighter than the other
        // is not a light either. What is left over is a lamp, a window, a sign, or
        // anything else that is brighter than everything near it.
        float3 excess = max(gathered - average * LightFloor, 0.0f);

        // The colour of it is pushed out of its own grey, which is what the water
        // of the drop does with a light: what is added is the colour of the lamp
        // and not the grey of the frame it was found in, so a drop next to the
        // tail light of a car is as red as the light is. Its brightness is left
        // where the gather put it, so a drop does not start to glow where the
        // scenery got brighter.
        float grey = dot(excess, float3(0.2126f, 0.7152f, 0.0722f));
        float3 light = max(grey + (excess - grey) * LightChroma, 0.0f);

        // What a drop takes from a light fades in as the drop comes near it
        // instead of switching on, which is what keeps the colour of a drop from
        // flickering while the scenery moves past it.
        float peak = max(light.r, max(light.g, light.b));

        output.light = light * smoothstep(LightRampLow, LightRampHigh, peak);
    }

    return output;
}

float4 PSMain(VSOutput input) : SV_TARGET
{
    float4 mask = maskTexture.Sample(linearClamp, input.atlas);
    float4 scene = sceneTexture.Sample(linearClamp, input.scene);

    float4 color = input.color * mask;

    // sceneComplement.x picks the complement, .y turns the sampling off
    float3 backdrop = 1.0f;
    if (sceneComplement.y > 0.5f)
        backdrop = sceneComplement.x > 0.5f ? (1.0f - scene.rgb) : scene.rgb;

    // A bright light must still leave refracted scene detail visible. Compress
    // its highlight smoothly, preserving hue instead of clipping RGB channels.
    float peak = max(input.light.r, max(input.light.g, input.light.b)) * 1.6f;
    float3 tint = input.light * (1.6f * 0.8f / (0.8f + peak));
    color.rgb *= backdrop + tint * (1.0f - backdrop);
    color.a *= 1.0f - 0.2f * (peak * 0.8f / (0.8f + peak));
    return color;
}
)";

        // Direct3D 9 transforms the drops with the fixed function pipeline, so
        // the light a drop gathers can only be found in a pixel shader, and
        // finding it again in the shader of every pixel of every drop is the whole
        // cost of the effect: it is a few hundred texture reads for every pixel
        // the drops cover. It is found once for the whole frame instead, into a
        // field an eighth of the target in each direction, and the drops read that
        // field with one tap each. The cost of the light no longer depends on how
        // many drops there are on the glass, and what is left of it is small
        // enough that the field can afford more taps per texel than a drop could.
        //
        // The number of cells the reach of a texel of the field is divided into
        // has to be the LightCellCount the backend passes in c0.z.
        inline const char* D3D9LightSource = R"(
static const int LightCellCount = 6;

sampler2D sceneSampler : register(s0);
float4 field : register(c0); // inverse width/height of the field, cells, radius

void GatherTap(float2 uv, float falloff, inout float3 energy, inout float3 plain, inout float weight, inout float falloffSum)
{
    // Outside-screen taps must not replicate a border lamp via clamp sampling.
    // Normalize both averages by the same remaining, visible part of the kernel.
    falloff *= step(0, uv.x) * step(uv.x, 1) * step(0, uv.y) * step(uv.y, 1);
    falloffSum += falloff;
    float3 source = tex2Dlod(sceneSampler, float4(uv, 0, 0)).rgb;
    float brightness = max(source.r, max(source.g, source.b));
    float saturation = (brightness - min(source.r, min(source.g, source.b))) / max(brightness, 0.001);
    float w = brightness * brightness * (1 + saturation) * falloff;
    energy += source * w;
    plain += source * falloff;
    weight += w;
}

float4 PSMain(float4 color : COLOR0, float2 atlas : TEXCOORD0, float2 scene : TEXCOORD1,
    float2 pixel : VPOS) : COLOR0
{
    // Where this texel of the field is on the target, in the very coordinates the
    // copy of the frame is in: the field and the frame are of the same picture,
    // which is what makes one tap of the field enough for a drop. The crop a game
    // asks the refraction to sample is not applied to it: a light is where it is
    // on the screen.
    float2 lightUV = (pixel + 0.5) * field.xy;
    float2 radius = float2(field.w * field.x / field.y, field.w);
    float2 cell = radius / field.z;
    float2 anchor = floor(lightUV / cell) * cell;

    float3 energy = 0, plain = 0;
    float weight = 0, falloffSum = 0;

    [loop] for (int y = -LightCellCount; y <= LightCellCount; ++y)
    {
        [loop] for (int x = -LightCellCount; x <= LightCellCount; ++x)
        {
            float2 corner = anchor + float2(x, y) * cell;
            float2 offset = (corner - lightUV) / radius;
            float distance2 = dot(offset, offset);
            float falloff = exp2(-2 * distance2) * (1 - smoothstep(0.75, 1, distance2));
            GatherTap(corner + float2(-0.25, -0.25) * cell, falloff, energy, plain, weight, falloffSum);
            GatherTap(corner + float2( 0.25, -0.25) * cell, falloff, energy, plain, weight, falloffSum);
            GatherTap(corner + float2(-0.25,  0.25) * cell, falloff, energy, plain, weight, falloffSum);
            GatherTap(corner + float2( 0.25,  0.25) * cell, falloff, energy, plain, weight, falloffSum);
        }
    }

    float3 gathered = energy / (weight + 0.5);
    float3 average = plain / max(falloffSum, 0.001);

    // What is left of the frame around the light is the light itself, and the
    // colour of it is not pushed out of its own grey here: a drop may not be
    // brighter than the light it took, and the field is where both are kept.
    return float4(max(gathered - average * 1.25, 0), 1);
}
)";

        // The drop itself: its shape, the copy of the frame behind it, and the
        // light it gathered out of that frame, which is one tap of the field the
        // shader above fills. Everything about the light a drop is drawn with is
        // what the renderers of Direct3D 10 and above do, so a drop looks the same
        // on Direct3D 9 as on them.
        inline const char* D3D9Source = R"(
sampler2D maskSampler : register(s0);
sampler2D sceneSampler : register(s1);
sampler2D lightSampler : register(s2);
float4 frame : register(c0); // inverse width/height, scene sampling, complement

float4 PSMain(float4 color : COLOR0, float2 atlas : TEXCOORD0, float2 scene : TEXCOORD1,
    float2 pixel : VPOS) : COLOR0
{
    bool lens = atlas.x < 0;
    if (lens) atlas.x += 2;
    float4 mask = tex2D(maskSampler, atlas);
    clip(mask.a * color.a - 0.001);
    float3 lightOut = 0;
    if (lens && frame.z > 0.5 && frame.w < 0.5)
    {
        float3 excess = tex2D(lightSampler, (pixel + 0.5) * frame.xy).rgb;

        // the same maths the other renderers do in their pixel shader
        float grey = dot(excess, float3(0.2126, 0.7152, 0.0722));
        float3 light = max(grey + (excess - grey) * 2.5, 0);
        float peak = max(light.r, max(light.g, light.b));
        lightOut = light * smoothstep(0.03, 0.20, peak);
    }
    float3 backdrop = 1;
    if (frame.z > 0.5)
    {
        backdrop = tex2D(sceneSampler, scene).rgb;
        if (frame.w > 0.5) backdrop = 1 - backdrop;
    }
    // Match the modern shader: preserve the refracted image under bright tint.
    float peak = max(lightOut.r, max(lightOut.g, lightOut.b)) * 1.6;
    float3 tint = lightOut * (1.6 * 0.8 / (0.8 + peak));
    float opacity = 1 - 0.2 * (peak * 0.8 / (0.8 + peak));
    return color * mask * float4(backdrop + tint * (1 - backdrop), opacity);
}
)";
        // OpenGL, same maths with the GLSL of a 1.20 context, which every
        // driver that can run a game provides.
        inline const char* OpenGLVertexSource = R"(
#version 120

uniform mat4 projection;

attribute vec3 position;
attribute vec4 color;
attribute vec2 atlas;
attribute vec2 scene;

varying vec4 vColor;
varying vec2 vAtlas;
varying vec2 vScene;

void main()
{
    gl_Position = projection * vec4(position, 1.0);
    vColor = color;
    vAtlas = atlas;
    vScene = scene;
}
)";

        inline const char* OpenGLFragmentSource = R"(
#version 120

uniform sampler2D sceneTexture;
uniform sampler2D maskTexture;
uniform vec2 uvOffset;
uniform vec2 uvScale;
uniform float sceneComplement;

varying vec4 vColor;
varying vec2 vAtlas;
varying vec2 vScene;

void main()
{
    vec4 mask = texture2D(maskTexture, vAtlas);
    vec4 scene = texture2D(sceneTexture, vScene * uvScale + uvOffset);

    vec4 color = vColor * mask;
    vec3 backdrop = sceneComplement > 0.5 ? (vec3(1.0) - scene.rgb) : scene.rgb;

    color.rgb *= backdrop;
    gl_FragColor = color;
}
)";

        // The same shader again for a core profile context, which refuses the
        // gl_FragColor, the varying and the attribute of version 120. An
        // application that asks for a 3.2 context or newer only accepts this one.
        inline const char* OpenGLVertexSourceCore = R"(
#version 150

uniform mat4 projection;

in vec3 position;
in vec4 color;
in vec2 atlas;
in vec2 scene;

out vec4 vColor;
out vec2 vAtlas;
out vec2 vScene;

void main()
{
    gl_Position = projection * vec4(position, 1.0);
    vColor = color;
    vAtlas = atlas;
    vScene = scene;
}
)";

        inline const char* OpenGLFragmentSourceCore = R"(
#version 150

uniform sampler2D sceneTexture;
uniform sampler2D maskTexture;
uniform vec2 uvOffset;
uniform vec2 uvScale;
uniform float sceneComplement;

in vec4 vColor;
in vec2 vAtlas;
in vec2 vScene;

out vec4 fragColor;

void main()
{
    vec4 mask = texture(maskTexture, vAtlas);
    vec4 scene = texture(sceneTexture, vScene * uvScale + uvOffset);

    vec4 color = vColor * mask;
    vec3 backdrop = sceneComplement > 0.5 ? (vec3(1.0) - scene.rgb) : scene.rgb;

    color.rgb *= backdrop;
    fragColor = color;
}
)";

        // A tiny shader for the test applications, it only fills a rectangle
        // with one colour so there is a UI the drops have to stay behind.
        inline const char* OpenGLSimpleVertexSource = R"(
#version 120

uniform mat4 projection;

attribute vec3 position;
attribute vec4 color;

varying vec4 vColor;

void main()
{
    gl_Position = projection * vec4(position, 1.0);
    vColor = color;
}
)";

        inline const char* OpenGLSimpleFragmentSource = R"(
#version 120

varying vec4 vColor;

void main()
{
    gl_FragColor = vColor;
}
)";

        inline const char* D3D11SimpleSource = R"(
cbuffer SimpleConstants : register(b0)
{
    float4x4 projection;
};

struct VSInput
{
    float3 position : POSITION;
    float4 color : COLOR;
};

struct VSOutput
{
    float4 position : SV_POSITION;
    float4 color : COLOR;
};

VSOutput SimpleVS(VSInput input)
{
    VSOutput output;
    output.position = mul(projection, float4(input.position, 1.0f));
    output.color = input.color;
    return output;
}

float4 SimplePS(VSOutput input) : SV_TARGET
{
    return input.color;
}
)";
    }
}
