param(
    [switch]$Verify,
    [switch]$Force,
    [string]$DxcPath
)
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$sourceRoot = Join-Path $root 'source/shaders'
$outputRoot = Join-Path $sourceRoot 'generated'
$cache = Join-Path $root 'build/shaders'
$fxc = Join-Path $PSScriptRoot 'x86/fxc.exe'
$utf8 = New-Object System.Text.UTF8Encoding($false)

function HashBytes([byte[]]$bytes) {
    $sha = [Security.Cryptography.SHA256]::Create()
    try { return [Convert]::ToBase64String($sha.ComputeHash($bytes)) }
    finally { $sha.Dispose() }
}
function FileHash([string]$file) { HashBytes ([IO.File]::ReadAllBytes($file)) }
function ReadSource([string]$file) {
    # Git's Windows checkout policy must not invalidate generated shaders.
    return [IO.File]::ReadAllText($file).Replace("`r`n", "`n")
}
function OutputHash([string]$file) {
    if ([IO.Path]::GetExtension($file) -eq '.h') { return HashBytes $utf8.GetBytes((ReadSource $file)) }
    return FileHash $file
}
function WriteText([string]$file, [string]$text) {
    [IO.Directory]::CreateDirectory((Split-Path $file -Parent)) | Out-Null
    [IO.File]::WriteAllText($file, $text, $utf8)
}
function FindDxc {
    if ($DxcPath) {
        if (!(Test-Path -LiteralPath $DxcPath)) { throw "DXC not found: $DxcPath" }
        return $DxcPath
    }
    if ($env:VULKAN_SDK) {
        $candidate = Join-Path $env:VULKAN_SDK 'Bin/dxc.exe'
        if (Test-Path -LiteralPath $candidate) { return $candidate }
    }
    $command = Get-Command dxc.exe -ErrorAction SilentlyContinue
    if ($command) { return $command.Source }
    throw 'Vulkan shader sources changed or their generated output is missing. Install Vulkan SDK DXC or pass -DxcPath. Unchanged, verified SPIR-V needs no SDK.'
}

# Each solution shares the generated files. Never compile the same output in
# competing prebuild events or publish a partial shader when compilation fails.
$mutex = New-Object System.Threading.Mutex($false, 'Local\XboxRainDropletsShaderBuild')
$locked = $false
try {
    try { $locked = $mutex.WaitOne(120000) }
    catch [System.Threading.AbandonedMutexException] { $locked = $true }
    if (!$locked) { throw 'Timed out waiting for the shader build.' }
    $manifest = Get-Content -LiteralPath (Join-Path $sourceRoot 'manifest.json') -Raw | ConvertFrom-Json
    if ($manifest.version -ne 1) { throw 'Unsupported shader manifest version.' }
    $receiptPath = Join-Path $outputRoot 'build.json'
    $receipts = @{}
    if (Test-Path -LiteralPath $receiptPath) {
        foreach ($receipt in (Get-Content -LiteralPath $receiptPath -Raw | ConvertFrom-Json)) {
            $receipts[$receipt.output] = $receipt
        }
    }
    $pending = @()
    $updated = @()
    foreach ($job in $manifest.jobs) {
        $inputs = 'shader-builder-v1|' + ($job | ConvertTo-Json -Depth 12 -Compress)
        foreach ($file in $job.sources) { $inputs += '|' + (HashBytes $utf8.GetBytes((ReadSource (Join-Path $sourceRoot $file)))) }
        $inputHash = HashBytes $utf8.GetBytes($inputs)
        $destination = Join-Path $outputRoot $job.output
        $old = $receipts[$job.output]
        $valid = $old -and $old.inputHash -eq $inputHash -and (Test-Path -LiteralPath $destination)
        if ($valid) { $valid = (OutputHash $destination) -eq $old.outputHash }
        if ($valid -and !$Force) { $updated += $old; continue }
        if ($Verify) { throw "Stale or missing shader: $($job.output). Run tools/BuildShaders.ps1." }

        $temporary = Join-Path $cache $job.output
        [IO.Directory]::CreateDirectory((Split-Path $temporary -Parent)) | Out-Null
        switch ($job.kind) {
            'fxc' {
                $arguments = @('/nologo') + @($job.flags) + @('/T', $job.profile, '/E', $job.entry, '/Fo', $temporary, (Join-Path $sourceRoot $job.sources[0]))
                & $fxc @arguments
                if ($LASTEXITCODE -ne 0) { throw "FXC failed: $($job.output)" }
            }
            'spirv' {
                $compiler = FindDxc
                $header = "// Generated by tools/BuildShaders.ps1. Edit source/shaders/vulkan/drops.hlsl.`n#pragma once`n#include <cstdint>`n"
                foreach ($stage in $job.stages) {
                    $binary = $temporary + '.' + $stage.entry + '.spv'
                    $arguments = @($job.flags) + @('-T', $stage.profile, '-E', $stage.entry, '-Fo', $binary, (Join-Path $sourceRoot $job.sources[0]))
                    & $compiler @arguments
                    if ($LASTEXITCODE -ne 0) { throw "DXC failed: $($stage.entry)" }
                    $bytes = [IO.File]::ReadAllBytes($binary)
                    if ($bytes.Length % 4 -ne 0 -or [BitConverter]::ToUInt32($bytes, 0) -ne 0x07230203) { throw 'Invalid SPIR-V output.' }
                    $header += "`ninline constexpr uint32_t $($stage.symbol)[] = {`n"
                    for ($i = 0; $i -lt $bytes.Length; $i += 4) {
                        $header += ('0x{0:x8}, ' -f [BitConverter]::ToUInt32($bytes, $i))
                        if (($i / 4) % 8 -eq 7) { $header += "`n" }
                    }
                    $header += "`n};`n"
                }
                WriteText $temporary $header
            }
            'embed' {
                $header = "// Generated by tools/BuildShaders.ps1. Edit the sources listed in source/shaders/manifest.json.`n#pragma once`nnamespace $($job.namespace) {`n"
                for ($i = 0; $i -lt $job.sources.Count; ++$i) {
                    $source = ReadSource (Join-Path $sourceRoot $job.sources[$i])
                    if ($source.Contains(')XRD"')) { throw 'Shader contains the reserved raw-string delimiter.' }
                    $header += 'inline constexpr char ' + $job.symbols[$i] + '[] = R"XRD(' + $source + ')XRD";' + "`n"
                }
                WriteText $temporary ($header + "}`n")
            }
            default { throw "Unknown shader build kind: $($job.kind)" }
        }
        $hash = OutputHash $temporary
        $pending += @{ temporary = $temporary; destination = $destination; hash = $hash }
        $updated += [ordered]@{ output = $job.output; inputHash = $inputHash; outputHash = $hash }
    }
    # Publish after every changed shader succeeds; unchanged files retain their
    # timestamps so C++ and resource compilation remain incremental.
    foreach ($item in $pending) {
        if (!(Test-Path -LiteralPath $item.destination) -or (OutputHash $item.destination) -ne $item.hash) {
            [IO.Directory]::CreateDirectory((Split-Path $item.destination -Parent)) | Out-Null
            [IO.File]::Copy($item.temporary, $item.destination, $true)
        }
    }
    if ($pending.Count) {
        WriteText $receiptPath (($updated | ConvertTo-Json -Depth 12) + "`n")
        Write-Output "Built $($pending.Count) shader outputs."
    }
    elseif ($Verify) { Write-Output "Verified $($updated.Count) shader outputs." }
}
finally {
    if ($locked) { $mutex.ReleaseMutex() }
    $mutex.Dispose()
}
